version: '3.7'
services:
  # Cohviz web application
  web:
    build: ./web
    volumes:
      - './GN_V110_XML:/code/cohapp/coherenceanalyzer/GN_V110_XML:ro'
      - 'static:/code/static:rw'
      - './cohviz.log:/code/cohviz.log:rw'
    environment:
      DB_SERVICE: postgres
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: iePh1phahY7aiteengoh
      DB_PORT: '5432'
      ALLOWED_HOSTS: 'localhost'
      CSRF_TRUSTED_ORIGINS: 'http://localhost:8080'
  # Web server
  nginx:
    image: nginx:1.21
    ports:
      - '8080:80'
    volumes:
      - './nginx/conf.d:/etc/nginx/conf.d:ro'
      - 'static:/www/static:ro'
  # Database
  postgres:
    image: postgres:14.0
    volumes:
      - './postgres/data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: iePh1phahY7aiteengoh
volumes:
  static:
