version: '2'
services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - ./web:/code
      - /usr/src/app/static
    command: /usr/local/bin/gunicorn mysite.wsgi:application -w 2 -b :8000
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes: 
      - /data:/var/lib/postgrsql/data