version: '3.7'
services:
  # Cohviz web application
  web:
    build: ./web
    ports:
      - '8000:8000'
    env_file: .env
    volumes:
      - ./GN_V110_XML:/code/cohapp/coherenceanalyzer/GN_V110_XML
  # The web server
  #nginx:
  #  restart: always
  #  build: ./nginx/
  #  ports:
  #    - "8080:80"
  #  volumes:
  #    - /www/static
  #  volumes_from:
  #    - web
  #  links:
  #    - "web:web"
  # The database
  postgres:
    image: postgres:14.0
    volumes:
      - ./postgres/data:/var/lib/postgrsql/data
    environment:
      POSTGRES_PASSWORD: iePh1phahY7aiteengoh
