version: '2'
services:
  db:
    image: postgres
    volumes: 
      - /data:/var/lib/postgrsql/data
  web:
    build: ./web
    command: python ./web/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  # nginx:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - web