version: '3.7'
services:
  # Cohviz web application
  web:
    build: ./web
    ports:
      - '8000:8000'
    env_file: .env
    volumes:
      - './GN_V110_XML:/code/cohapp/coherenceanalyzer/GN_V110_XML:ro'
      - 'static:/code/static:rw'
      - './cohviz.log:/code/cohviz.log:rw'
  # Web server
  nginx:
    image: nginx:1.21
    ports:
      - '8080:80'
    volumes:
      - './nginx/conf.d:/etc/nginx/conf.d:ro'
      - 'static:/www/static:ro'
  # Database
  postgres:
    image: postgres:14.0
    volumes:
      - './postgres/data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: iePh1phahY7aiteengoh
volumes:
  static:
